env: local
kafka:
  bootstrapServers: "localhost:9092"
  topics:
    pageContext: "page_context"
    campaigns: "ad_campaigns"
    decisions: "ad_decisions"
mongo:
  uri: "${MONGO_URI}"
  database: "realtime_ads"